version: "3"
services:
  prod:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: herzen-schedule-bot
    volumes:
      - /etc/localtime:/etc/localtime
